### ISSUE TITLE
Exception in thread "Thread-3" java.lang.NullPointerException

### ISSUE THREAD

**Issue by LyleLeo** [zarakfarid/YCSB-0.12.0-CouchDB-Binding#1]
`java.lang.ClassNotFoundException: com.yahoo.ycsb.db.couchdb.CouchdbClient
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:38)
        at com.yahoo.ycsb.Client.initDb(Client.java:873)
        at com.yahoo.ycsb.Client.main(Client.java:759)
Exception in thread "Thread-3" java.lang.NullPointerException
        at com.yahoo.ycsb.ClientThread.run(Client.java:424)
        at java.lang.Thread.run(Thread.java:748)`

When i use 'ycsb load couchdb -s -P C:\ycsb-0.1.4/workloads/workloada -p hosts=localhost:5984  > outputLoad.txt',i get the exception like this.Do you have any idea to solve this problem?

**Comment by zarakfarid** [comment]
Did you replace or add content from the "bin" folder as it has the mapping and placed the couchdb folder as well?
